copy LaRonde_mine.html LaRonde_mine.html 
copy LaRonde_mine.html LaRondeZone5_mine.html
copy LaRonde_mine.html Goldex_mine.html
copy LaRonde_mine.html Meadowbank_mine.html
copy LaRonde_mine.html CanadianMalartic_mine.html
copy LaRonde_mine.html Meliadine_mine.html
copy LaRonde_mine.html Operationaldatasegment1.html
copy LaRonde_mine.html DetourLake_mine.html
copy LaRonde_mine.html Macassa_mine.html
copy LaRonde_mine.html PinosAltos_mine.html
copy LaRonde_mine.html LaIndia_mine.html
copy LaRonde_mine.html Kittila_mine.html
copy LaRonde_mine.html Fosterville_mine.html
copy LaRonde_mine.html LaRonde_mineEsg.html
copy LaRonde_mine.html LaRondeZone5_mineEsg.html
copy LaRonde_mine.html Goldex_mineEsg.html
copy LaRonde_mine.html Meadowbank_mineEsg.html
copy LaRonde_mine.html CanadianMalartic_mineEsg.html
copy LaRonde_mine.html Meliadine_mineEsg.html
copy LaRonde_mine.html Operationaldatasegment1.html
copy LaRonde_mine.html DetourLake_mineEsg.html
copy LaRonde_mine.html Macassa_mineEsg.html
copy LaRonde_mine.html PinosAltos_mineEsg.html
copy LaRonde_mine.html LaIndia_mineEsg.html
copy LaRonde_mine.html Kittila_mineEsg.html
copy LaRonde_mine.html Fosterville_mineEsg.html

